name: 'Set Go'
description: like actions/setup-go but worse
inputs:
  go-version:
    required: true
    description: "version of go to install"
  install-dir:
    required: false
    description: "where to install"
outputs:
  GOCACHE:
    description: go env GOCACHE
    value: ${{ steps.install-go.outputs.GOCACHE }}
runs:
  using: composite
  steps:
    - id: install-go
      shell: bash
      env:
        INSTALL_GO_VERSION: ${{ inputs.go-version }}
        INSTALL_GO_TARGET_DIR: ${{ inputs.install-dir }}
      run: src/install-go
