name: 'Set Go'
description: like actions/setup-go but worse
inputs:
  go-version:
    required: true
    description: |
      The version of go to install. This must be the exact version number. No fancy semver tricks here.
  install-dir:
    required: false
    description: |
      Where to install go. Default: <tool_cache>/go/<go-version>/x64
outputs:
  GOCACHE:
    description: go env GOCACHE
    value: ${{ steps.install-go.outputs.GOCACHE }}
  GOMODCACHE:
    description: go env GOMODCACHE
    value: ${{ steps.install-go.outputs.GOMODCACHE }}
  GOPATH:
    description: go env GOPATH
    value: ${{ steps.install-go.outputs.GOPATH }}
  GOROOT:
    description: go env GOROOT
    value: ${{ steps.install-go.outputs.GOROOT }}
  GOTOOLDIR:
    description: go env GOTOOLDIR
    value: ${{ steps.install-go.outputs.GOTOOLDIR }}
runs:
  using: composite
  steps:
    - id: install-go
      shell: bash
      env:
        INSTALL_GO_TOOL_CACHE: ${{ runner.tool_cache }}
        INSTALL_GO_VERSION: ${{ inputs.go-version }}
        INSTALL_GO_TARGET_DIR: ${{ inputs.install-dir }}
      run: src/install-go
