#!/bin/bash

set -ex

export GO111MODULE=off

homedir() {
  if [ "$(uname -s)" = "Windows" ]; then
    echo "$USERPROFILE"
  else
    echo "$HOME"
  fi
}

sdk_dir() {
  echo "$(homedir)/sdk"
}

gobin() {
  res="$(go env GOBIN)"
  [ -n "$res" ] || res="$(go env GOPATH)/bin"
  echo "$res"
}

GO_VERSION="${GO_VERSION:-1.15.4}"

go get -v "golang.org/dl/go$GO_VERSION"
"$(gobin)/go$GO_VERSION" download
