name: ci
on: [push, pull_request, workflow_dispatch]
jobs:
  old:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: go version
        run: |
          set -x
          go version
          go env
          which go
          echo $PATH
          which go
  set-go:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: env
      - run: |
          ls -haltr /opt/hostedtoolcache/go
      - name: setup go
        env:
          INSTALL_GO_VERSION: 1.15.2
        run: src/install-go

#          go$goversion download
#  new:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: setup go
#        run: |
#          echo "PATH=$GOROOT_1_15_X64/bin:$PATH" >> $GITHUB_ENV
#          echo "GOROOT=$GOROOT_1_15_X64" >> $GITHUB_ENV
#      - name: go verion
#        run: |
#          go version
#          go env
