name: ci
on: [push, pull_request, workflow_dispatch]
jobs:
  old:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: go version
        run: |
          set -x
          go version
          go env
          which go
          echo $PATH
          which go
  set-go:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        id: setup-go
        env:
          INSTALL_GO_VERSION: 1.15.2
        run: src/install-go
      - run: echo '${{ toJson(steps.setup-go.outputs) }}'

#          go$goversion download
#  new:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: setup go
#        run: |
#          echo "PATH=$GOROOT_1_15_X64/bin:$PATH" >> $GITHUB_ENV
#          echo "GOROOT=$GOROOT_1_15_X64" >> $GITHUB_ENV
#      - name: go verion
#        run: |
#          go version
#          go env
