name: ci
on: [push, pull_request, workflow_dispatch]
jobs:
  logger:
    runs-on: ubuntu-20.04
    steps:
      - name: log something
        run: |
          echo ::warning::this is a warning
          echo ::error::this is an error
          echo ::info::this is some info 
  old:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.14'
      - name: go verion
        run: |
          go version
          go env
  dl:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          ls -haltr /opt/hostedtoolcache/go
      - name: setup go
        env:
          goversion: 1.14.7
        run: |
          set -x
          go get golang.org/dl/go$goversion
#          go$goversion download
  new:
    runs-on: ubuntu-20.04
    steps:
      - name: setup go
        run: |
          echo "PATH=$GOROOT_1_15_X64/bin:$PATH" >> $GITHUB_ENV
          echo "GOROOT=$GOROOT_1_15_X64" >> $GITHUB_ENV
      - name: go verion
        run: |
          go version
          go env
