name: ci
on: [ push, pull_request, workflow_dispatch ]
jobs:
#  old:
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ ubuntu-20.04, macos-latest, windows-2019 ]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/setup-go@v2
#        with:
#          go-version: '1.15.2'
#      - name: go version
#        shell: bash
#        run: |
#          set -x
#          go version
#          go env
#          which go
#          echo $PATH
#          which go
  set-go:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-2019 ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - run: env
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setgo
        id: setgo
        with:
          go-version: "1.16beta1"
      - env:
          outs: ${{ toJson(steps.setgo.outputs) }}
        run: echo $outs | jq .

#          go$goversion download
#  new:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: setup go
#        run: |
#          echo "PATH=$GOROOT_1_15_X64/bin:$PATH" >> $GITHUB_ENV
#          echo "GOROOT=$GOROOT_1_15_X64" >> $GITHUB_ENV
#      - name: go verion
#        run: |
#          go version
#          go env
