name: ci
on: [push, pull_request]
jobs:
  new:
    runs-on: ubuntu-20.04
    steps:
      - run: docker images
      - run: docker pull blacktop/elasticsearch:7.1
      - run: docker pull elasticsearch:7.1.0
      - run: docker pull percona:5.7.21
      - name: setup go
        run: |
          echo "PATH=$GOROOT_1_15_X64/bin:$PATH" >> $GITHUB_ENV
          echo "GOROOT=$GOROOT_1_15_X64" >> $GITHUB_ENV
      - name: go verion
        run: |
          go version
          go env
